name = "AOC2022"
uuid = "6cb0755e-dadc-4b5d-8b2d-3061c9353cb5"
authors = ["Alexandre Magueresse <alexandre.magueresse@monash.edu>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
